version: '3.8'

x-airflow-common: &airflow-common
  build: .
  environment:
    &airflow-common-env
    AIRFLOW_UID: '50000'
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./scripts:/opt/airflow/scripts

services:
  postgres:
    image: 'postgres:13'
    container_name: flightsense-postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"

  airflow-webserver:
    <<: *airflow-common
    container_name: flightsense-webserver
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - airflow-init
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    container_name: flightsense-scheduler
    command: scheduler
    depends_on:
      - postgres
      - airflow-init
    restart: always

  airflow-triggerer:
    <<: *airflow-common
    container_name: flightsense-triggerer
    command: triggerer
    depends_on:
      - postgres
      - airflow-init
    restart: always

  airflow-init:
    <<: *airflow-common
    container_name: flightsense-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init &&
        airflow users create \
          --username admin \
          --password admin \
          --firstname Anonymous \
          --lastname User \
          --role Admin \
          --email admin@example.com