FROM apache/airflow:2.8.1

USER root

USER airflow


RUN pip install --no-cache-dir \
    "apache-airflow-providers-google==10.13.0" \
    "pandas-gbq==0.22.0" \
    "google-cloud-storage==2.16.0" \
    "scikit-learn==1.5.0" \
    "xgboost==2.0.3" \
    "dbt-bigquery==1.8.0"